cognome = input("inserisci il cognome")
nome = input ("inserisci nome")
print ("ciao",nome,cognome,"ora svolgi l esercizio")
num1= input ("dammi il primo numero")
num2= input ("dammi il secondo numero")
print("il primo numero é", num2,"il secondo numero é" ,num1)